// Model fetching — the single place that knows WHERE models come from.
//
// Three inputs feed the form engine (findings-a12.md §1, §5):
//   - documentModel (JSON)  — from the A12 Data Service (Java kernel serves it)
//   - validation.js (JS source string) — generated by the JVM kernel, fetched as text
//   - formModel (JSON)      — from the Node model-lifecycle service (generated default)
//
// Every URL here is centralized + annotated // VERIFY because the exact A12
// model-serving paths are not pinned in the docs we have. Resolve them against
// the live stack, then this is the only module to touch.

export interface LoadedModels {
  documentModelAsString: string; // raw JSON text — the serializer deserializes from string
  formModelAsJson: unknown; // parsed JSON
  validationCode: string; // JS source string for GeneratedCodeAccessorFactory
}

// VERIFY: A12 Data Service model-artifact URLs. The form-engine bootstrap example
// fetches `models/documentModel.json` and `models/validation.js` relative to the
// app; with our nginx same-origin proxy the Data Service equivalents are assumed
// to live under /api. Confirm the real paths the running kernel serves (they may
// be JSON-RPC ops like GET_DOCUMENT_MODEL rather than static files).
function documentModelUrl(type: string): string {
  return `/api/models/${type}/documentModel.json`; // VERIFY
}
function validationCodeUrl(type: string): string {
  return `/api/models/${type}/validation.js`; // VERIFY
}

// Form models come from the Node model-lifecycle service (generated default,
// persisted) per the integration contract: /lifecycle/form-model/<type>.
function formModelUrl(type: string): string {
  return `/lifecycle/form-model/${type}`;
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { Accept: "application/json, text/javascript" } });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: HTTP ${res.status} ${res.statusText}`);
  return res.text();
}

/** Fetch the three model inputs for a content type, in parallel. */
export async function loadModels(type: string): Promise<LoadedModels> {
  const [documentModelAsString, formModelText, validationCode] = await Promise.all([
    fetchText(documentModelUrl(type)),
    fetchText(formModelUrl(type)),
    fetchText(validationCodeUrl(type)),
  ]);
  return {
    documentModelAsString,
    formModelAsJson: JSON.parse(formModelText),
    validationCode,
  };
}
