// Model fetching — the single place that knows WHERE models come from.
//
// Three inputs feed the form engine (findings-a12.md §1, §5):
//   - documentModel (JSON)  — from the A12 Data Service (Java kernel serves it)
//   - validation.js (JS source string) — generated by the JVM kernel, fetched as text
//   - formModel (JSON)      — from the Node model-lifecycle service (generated default)
//
// Every URL here is centralized + annotated // VERIFY because the exact A12
// model-serving paths are not pinned in the docs we have. Resolve them against
// the live stack, then this is the only module to touch.

import { getToken, logout } from "../lib/auth.ts";

export interface LoadedModels {
  documentModelAsString: string; // raw JSON text — the serializer deserializes from string
  formModelAsJson: unknown; // parsed JSON
  validationCode: string; // JS source string for GeneratedCodeAccessorFactory
}

// A12 model-serving endpoints — CONFIRMED against the live stock Data Service
// (QA-LOG B9): the kernel serves each model at `/api/v2/models/<ModelName>` and
// the generated validation code at `/api/v2/models/<DM>/validationCode`. Document
// + form models share the same endpoint (distinguished by the `_DM`/`_FM` name).
// A content type maps to `<Type>_DM` / `<Type>_FM` (e.g. page -> Page_DM/Page_FM).
// `type` may be a bare type ("location") OR a model id ("Location_DM") — when
// editing, the resolved item carries the model id. Strip any `_DM`/`_FM` suffix
// first, then normalize case, so "Location_DM" -> "Location_FM" (not the buggy
// "Location_dm_FM" — QA-LOG B18).
function modelName(type: string, suffix: "DM" | "FM"): string {
  const base = type.replace(/_(DM|FM)$/i, "");
  const t = base.charAt(0).toUpperCase() + base.slice(1).toLowerCase();
  return `${t}_${suffix}`;
}
function documentModelUrl(type: string): string {
  return `/api/v2/models/${modelName(type, "DM")}`;
}
function validationCodeUrl(type: string): string {
  return `/api/v2/models/${modelName(type, "DM")}/validationCode`;
}
function formModelUrl(type: string): string {
  return `/api/v2/models/${modelName(type, "FM")}`;
}

async function fetchText(url: string): Promise<string> {
  const token = getToken();
  const res = await fetch(url, {
    headers: {
      Accept: "application/json, text/javascript",
      "Accept-Language": "en",
      ...(token ? { Authorization: `UAABearer ${token}` } : {}),
    },
  });
  if (res.status === 401) {
    logout();
    throw new Error("Your session has expired — please log in again.");
  }
  if (!res.ok) throw new Error(`Failed to fetch ${url}: HTTP ${res.status} ${res.statusText}`);
  return res.text();
}

/** Fetch just the Document Model JSON (string) for a type — used by the simple form. */
export async function loadDocumentModel(type: string): Promise<string> {
  return fetchText(documentModelUrl(type));
}

/** Fetch the three model inputs for a content type, in parallel. */
export async function loadModels(type: string): Promise<LoadedModels> {
  const [documentModelAsString, formModelText, validationCode] = await Promise.all([
    fetchText(documentModelUrl(type)),
    fetchText(formModelUrl(type)),
    fetchText(validationCodeUrl(type)),
  ]);
  return {
    documentModelAsString,
    formModelAsJson: JSON.parse(formModelText),
    validationCode,
  };
}
