#
# SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
#
# Copyright (c) 2012-2026 mgm technology partners GmbH
#
# Dual License
# ------------
# This source file is part of the mgm A12 Platform and available under
# a choice of two different licenses:
#
# 1. Open-Source License - EUPL v1.2
#    You may redistribute and/or modify this file under the terms of the
#    European Union Public License, version 1.2 - see https://eupl.eu/.
#
# 2. Commercial License
#    Alternatively, you may obtain a commercial license from
#    mgm technology partners GmbH, that permits use of this software
#    under different terms (including support and maintenance services).
#
#    Please contact a12-license@mgm-tp.com for more information.
#
# You must select and comply with exactly one of the above license options.
#
# Warranty Disclaimer (applies to either option)
# ----------------------------------------------
# THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
# WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
# LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
#

roles:
  - name: admin
    description: admin role
    accessRights:
      - DOCUMENT_CREATE
      - DOCUMENT_UPDATE
      - DOCUMENT_PARTIAL_UPDATE
      - DOCUMENT_DELETE
      - ATTACHMENT_UPLOAD
      - MODEL_MANAGE
      - QUERY
  - name: systemAdmin
    description: system admin role
    accessRights:
      - ACCESS_ACTUATOR
      - MANAGE_CACHES
      - RELOAD_AUTH_RULES
  - name: user
    description: user role
    accessRights:
      - DOCUMENT_CREATE
      - DOCUMENT_UPDATE
      - DOCUMENT_PARTIAL_UPDATE
      - DOCUMENT_DELETE
      - MODEL_READ
      - ATTACHMENT_UPLOAD
      - QUERY
